#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=3
#SBATCH --time=00:10:00
#SBATCH --output=log.slurm.stdOut
#SBATCH --constraint=haswell

cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior
source env.CQL3D_examples
export PYTHONPATH=$PWD/_exec:PYTHONPATH
mkdir www
ips.py --config=CQL3D_basic_example_pegasus.config --platform=conf.ips.cori --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh
