#!/bin/bash -l
#SBATCH --account=m77
#SBATCH --partition=regular
#SBATCH --nodes=16
#SBATCH --constraint=haswell
#SBATCH --time=02:30:00
#SBATCH --output=log.slurm.stdOut
cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior

# Uncomment next line to use the local wrappers (e.g for development)
source $LOCAL_WRAPPER_PATH/use_local_wrappers
source $IPS_WRAPPER_PATH/env.TORLH_binary
source $IPS_WRAPPER_PATH/env.COMPX_codes
ips.py --config=PST_LH.config --platform=conf.ips.cori --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh

