#!/bin/bash
#SBATCH -N 2
#SBATCH -C haswell
#SBATCH -q debug
#SBATCH -J GITR_test
#SBATCH -t 00:20:00

#OpenMP settings:
export OMP_NUM_THREADS=24
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
export MPICH_RANK_REORDER_METHOD=0

source /project/projectdirs/atom/atom-install-edison/GITR/env.edison.sh
source /scratch1/scratchdirs/tyounkin/mq4/solps_ft_gitr/env.ips.edison
#run the application:
srun -N 2 /project/projectdirs/atom/atom-install-edison/GITR/build/GITR
#srun -n 10 -c 24 --cpu_bind=cores /project/projectdirs/atom/atom-install-edison/GITR/build/GITR
