#!/bin/bash -x
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -t 00:05:00
#SBATCH -o ips.out
#SBATCH -e ips.err

export IPS_WRAPPER_PATH=/global/homes/r/rwp/GENRAY_CQL3D_DIIID_LH/ips-wrappers
export PYTHONPATH=$IPS_WRAPPER_PATH/utilities:$PYTHONPATH

export UPDATE_STATE_BIN_DIR=/global/common/software/atom/cori/share/ntcc_intel/bin
export PATH=$UPDATE_STATE_BIN_DIR:$PATH

source $IPS_WRAPPER_PATH/env.COMPX_codes

source /global/common/software/atom/cori/ips-framework-new/bin/activate
ips.py --config=GENRAY_CQL3D_LH.config --platform=conf.ips.cori --log=ips.log
