#!/bin/bash -x
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -t 00:10:00
#SBATCH -o ips.out
#SBATCH -e ips.err

source /global/common/software/atom/cori/ips-wrappers/env.COMPX_codes

export UPDATE_STATE_BIN_DIR=/global/common/software/atom/cori/share/ntcc_intel/bin
export PATH=$UPDATE_STATE_BIN_DIR:$PATH

source /global/common/software/atom/cori/ips-framework-new/bin/activate
ips.py --config=GENRAY_CQL3D_LH.config --platform=conf.ips.cori --log=ips.log
