#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1
#SBATCH --time=10:00
#SBATCH --output=log.slurm.stdOut
#SBATCH --constraint=haswell

cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior
source $IPS_WRAPPER_PATH/env.ips.cori   # N.B. This is the Cori installation
# Switch to use the local wrappers (e.g for development)
#source $LOCAL_WRAPPER_PATH/use_local_wrappers

source $IPS_WRAPPER_PATH/env.COMPX_codes
$IPS_PATH/bin/ips.py --config=GENRAY_CQL3D_LH.config --platform=conf.ips.edison --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh
