#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1
#SBATCH --time=00:06:00
#SBATCH --output=log.slurm.stdOut

cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior
source $IPS_DIR/ips-wrappers/env.ips.edison
echo 'IPS_WRAPPER_PATH = ' $IPS_WRAPPER_PATH
# Uncomment next line to use the local wrappers with new-ips package
source $LOCAL_WRAPPER_PATH/env.new-ips-local-wrappers.cori
source /global/common/software/atom/cori/ips-framework-new/bin/activate
ips.py --config=restart_seq_model_sim.config --platform=conf.ips.edison --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh

