#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1
#SBATCH --time=00:07:00
#SBATCH --output=log.slurm.stdOut
#SBATCH --constraint=haswell

source $U2115/ips-wrappers/env.ips.cori
#source $IPS_WRAPPER_PATH_CORI/env.ips.cori
mkdir www
$IPS_PATH/bin/ips.py --config=sequential_model_simulation.config --platform=conf.ips.cori --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh

