#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1 
#SBATCH --time=10:00
#SBATCH --output=log.slurm.stdOut
#SBATCH --constraint=haswell

cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior
source $U2115/ips-wrappers/env.ips.cori
#source $IPS_DIR/ips-wrappers/env.ips
#export PYTHONPATH=$PWD/_exec:PYTHONPATH
$IPS_PATH/ips.py --config=GENRAY_SA.config --platform=conf.ips.cori --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh
