#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1
#SBATCH --time=00:02:00
#SBATCH --output=log.slurm.stdOut

cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior

# Production
 source /project/projectdirs/atom/atom-install-edison/ips-wrappers/env.ips.edison

# dbb_devel
#source /project/projectdirs/atom/users/u2115/ips-wrappers/env.ips.edison

# Greendl1
#source /project/projectdirs/atom/users/greendl1/code/ips-wrappers/env.ips.edison

echo 'IPS_WRAPPER_PATH = ' $IPS_WRAPPER_PATH
export PYTHONPATH=./_exec:$PYTHONPATH
$IPS_PATH/bin/ips.py --config=ABC_simulation.config --platform=conf.ips.edison --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh
