touch ../baserun/b2ag.dat
sleep 1
touch ../baserun/b2ag.prt
sleep 1
touch ../baserun/b2fgmtry
sleep 1
touch ../baserun/b2ah.dat
sleep 1
touch ../baserun/b2ah.prt
sleep 1
touch ../baserun/b2fpardf
sleep 1
touch ../baserun/b2ar.dat
sleep 1
touch ../baserun/b2ar.prt
sleep 1
touch ../baserun/b2frates
sleep 1
touch ../baserun/b2ai.dat
sleep 1
touch ../baserun/b2ai.prt
sleep 1
touch ../baserun/b2fstati
sleep 1
touch b2fstati
