#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1
#SBATCH --time=00:04:00
#SBATCH --output=log.slurm.stdOut
#SBATCH --constraint=cpu

cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior

source env.ABC_example
mkdir www
ips.py --config=ABC_simulation.config --platform=conf.ips.perlmutter --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
