#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1
#SBATCH --time=00:07:00
#SBATCH --output=log.slurm.stdOut
#SBATCH --constraint=cpu

mkdir www
module load python
conda dactivate
conda activate my_ips_env
source $IPS_WRAPPER_PATH/env.run.perlmutter
source $IPS_WRAPPER_PATH/env.TORIC_binary
ips.py --config=TORIC_ITER_TSC.config --platform=conf.ips.perlmutter --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh

