#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=1
#SBATCH --time=00:07:00
#SBATCH --output=log.slurm.stdOut
#SBATCH --constraint=cpu

mkdir www

source $IPS_WRAPPER_PATH/env.run.perlmutter
source $IPS_WRAPPER_PATH/env.COMPX_codes
ips.py --config=CQL3D_Cmod_LH_example_torlh.config --platform=conf.ips.perlmutter --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh

