#!/bin/bash -l
#SBATCH --account=atom
#SBATCH --partition debug
#SBATCH --nodes=3 
#SBATCH --time=00:05:00
#SBATCH --output=log.slurm.stdOut
cd $SLURM_SUBMIT_DIR   # optional, since this is the default behavior
#source /project/projectdirs/atom/users/u2115/ips-wrappers/env.ips.edison
source $IPS_DIR/ips-wrappers/env.ips.edison 
$IPS_PATH/bin/ips.py --config=CQL3D_SA.config --platform=conf.ips.edison --log=log.framework 2>>log.stdErr 1>>log.stdOut
egrep -i 'error' log.* > log.errors
./setPermissions.sh

